@Library('Shared') _
pipeline {
    agent any
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag')
    }

    stages {

        stage("Workspace cleanup"){
            steps{
                cleanWs()
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/Rashi228/wanderlust-project.git","main")
                }
            }
        }
        
        stage('Verify Tags') {
            steps {
                echo "Frontend Tag: ${params.FRONTEND_DOCKER_TAG}"
                echo "Backend Tag: ${params.BACKEND_DOCKER_TAG}"
            }
        }
        
        // ✅ WINDOWS FIX (NO sed, NO sh)
        stage("Update Kubernetes manifests"){
            steps{
                script{
                    // Backend YAML update
                    def backendFile = readFile 'kubernetes/backend.yaml'
                   backendFile = backendFile.replaceAll(
                    /wanderlust-backend-beta:.*/,
                 "wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}"
              )
                    writeFile file: 'kubernetes/backend.yaml', text: backendFile

                    // Frontend YAML update
                    def frontendFile = readFile 'kubernetes/frontend.yaml'
                    frontendFile = frontendFile.replaceAll(
                        'wanderlust-frontend-beta:.*',
                        "wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}"
                    )
                    writeFile file: 'kubernetes/frontend.yaml', text: frontendFile
                }
            }
        }
        
        // ✅ FIXED GITHUB PUSH
        stage("Git Push Updated Manifests"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        bat '''
                        git config user.email "guptarashi2201@gmail.com"
                        git config user.name "Rashi228"

                        git add .
                        git commit -m "Updated image tags" || exit 0

                        git push https://github.com/Rashi228/wanderlust-project.git main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            emailext attachLog: true,
            subject: "✅ Deployment Success - ${env.BUILD_NUMBER}",
            body: "Your app deployed successfully 🚀",
            to: 'guptarashi2201@gmail.com'
        }

        failure {
            emailext attachLog: true,
            subject: "❌ Deployment Failed - ${env.BUILD_NUMBER}",
            body: "Something failed ❌ check Jenkins logs",
            to: 'guptarashi2201@gmail.com'
        }
    }
}
